GET http://localhost:8080/employees

###

GET http://localhost:8080/employees/1

###

POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Martin Moser",
  "hireDate": "2020-05-31",
  "salary": 1890,
  "canOperate": "HEAVY",
  "age": 23
}

###

PUT http://localhost:8080/employees
Content-Type: application/json

{
  "id": 1,
  "name": "Martina Muster",
  "hireDate": "2019-01-12",
  "salary": 1900,
  "canOperate": "MEDIUM",
  "age": 34
}

### DELETE

DELETE http://localhost:8080/employees/1
