GET http://localhost:8080/materials

###

GET http://localhost:8080/materials/1

###

POST http://localhost:8080/materials
Content-Type: application/json

{
  "name": "Schwarzes Granulat",
  "code": "MAT-SW01",
  "inStock": true
}

###

PUT http://localhost:8080/materials
Content-Type: application/json

{
  "id": 1,
  "name": "Schwarzes Granulat",
  "code": "MAT-SW01",
  "inStock": false
}

###

DELETE http://localhost:8080/materials/1
