@startuml
class Employee
class Machine
enum MachineType
class Material
class Product
class Production

Product "1" --- "*" Production
Employee "1" --- "*" Production
Machine "1" --- "*" Production
Product "*" --- "1" Material

class Employee {
    + name
    + age
    + salary
    + hireDate
    + canOperate
}

class Machine {
    + machineType
}

enum MachineType {
    HEAVY,
    MEDIUM,
    LIGHT
}

class Material {
    + name
    + code
    + inStock
}

class Product {
    + name
    + material
    + requiredMachineType
}

class Production {
    + employee
    + machine
    + product
}

@enduml
